### ISSUE TITLE
If only one language allowed - set also as default lang

### ISSUE THREAD

**Issue by luke-** [humhub/humhub-modules-translation-manager#1]
If the language was limited by the translation manager module, make sure the "defautl language" of the installation is also - changed.

+ Check what happens with users already switched to another language. show warning and reset all user languages?

**Comment by luke-** [comment]
+ check problem with login page in wrong language

**Comment by luke-** [comment]
+ handle user languages

**Comment by yurabakhtin** [comment]
@luke- MR https://git.humhub.org/professional/translation-manager/-/merge_requests/3

> 1) If the language was limited by the translation manager module, make sure the "defautl language" of the installation is also - changed.

I implemented to change default language to first enabled language, e.g. if default was "English" and the enabled/allowed languages were updated to "Deutsch" and "Français" then first "Deutsch" will be used as new default language.

> 2) Check what happens with users already switched to another language. show warning and reset all user languages?

I implemented to update languages of all users to default languages if they still used the disabled languages. I.e. if some users used "Español" or "Svenska" but admin update enabled/allowed languages to "Deutsch" and "Français"(even if default language was not changed) then languages of such users will be updated to current default(e.g. "Deutsch").
I did this because no reason to keep in DB not allowed language for users because they cannot select it(disabled langauge) on profile edit form.

Admin may see the following warnings after update the enabled/allowed languages:

<img width="862" alt="lang_warnings" src="https://user-images.githubusercontent.com/6995524/95989107-81934c80-0e32-11eb-81b9-051315c112f9.png">

> 3) check problem with login page in wrong language

I have tested the login page and for me it looks correctly. Please explain how it must work.
What I tested:
- on first open login page I see default language(e.g. "English") is used,
- if I log out from user which has "Français" then the login page uses the "Français" language, for me it is expected, is ok?

> 4) handle user languages

It is not enough clear what to do, probably I already fixed this as point 2), if no please give me more details, thanks.

**Comment by luke-** [comment]
Awesome! Release with module version 1.0.3
