### ISSUE TITLE
Allow "Manual Overwrites" for Profile Fields 

### ISSUE THREAD

**Issue by luke-** [humhub/humhub-modules-translation-manager#4]
Currently the Translation Manager only allows the user to overwrite texts found via search.

For profile fields or profile field categories, however, users can assign labels dynamically, which then cannot be translated. 

The Translation Manager should either include dynamic texts (profiles) or offer a possibility to add overwrites manually.

**Comment by yurabakhtin** [comment]
@luke- MR https://git.humhub.org/professional/translation-manager/-/merge_requests/4

Please note I put a config array in the `TranslationHelper`:

```
$dbSources = [
    'user' => [
        'profile_field' => [
            'model' => '\humhub\modules\user\models\ProfileField',
            'attributes' => ['title', 'description'],
        ],
        'profile_field_category' => [
            'model' => '\humhub\modules\user\models\ProfileFieldCategory',
            'attributes' => ['title', 'description'],
        ],
    ],
];
```

but I am not sure that is good place, I think better if we will keep this in each module where some models have translatable attributes, e.g. here `protected/humhub/modules/user/Module.php` we can create new method like `getTranslatableAttributes()` or `getTranslatableModels()` that will return array so in the translation manager module we will know where search additional messages.
But in order to implement this in the translation manager module we should firstly modify core modules at least module `user` and then the translation manager module will can be used only for version since `1.7` as I understand.
Let me know if we need this solution.

This is my test and some explanations:
<img width="855" alt="test_translate_profile_fields" src="https://user-images.githubusercontent.com/6995524/96733776-8328bb80-13c2-11eb-8251-b0cf9978adb6.png">

**Comment by luke-** [comment]
Awesome thanks!

**Comment by luke-** [comment]
I think we can leave the Config Array in Translation Helper for the current usecase. 
If there are more cases in the future, we can think of an interface or something similar in the core.
